### ISSUE TITLE
vite preview + directory listings? should work without index.html file

### ISSUE THREAD

**Issue by milahu** [wesbos/vite-plugin-list-directory-contents#4]
when i run `npx vite preview` without an `index.html` i still get `Cannot GET /` (http 404)

**Comment by wesbos** [comment]
I'm actually not familiar with vite preview. What's the difference vs regular vite dev server?

**Comment by milahu** [comment]
you run `vite build` to generate `dist/`
then you run `vite preview` to serve the files in `dist/`

i just tried running `vite` but still get http 404, no directory listing : /

<details>
<summary>
vite.config.js
</summary>

```js
import { defineConfig } from 'vite';
import { directoryPlugin } from 'vite-plugin-list-directory-contents';

const assetsDir = '';
//const assetsDir = 'assets/';

const outputDefaults = {
  // remove hashes from filenames
  entryFileNames: `${assetsDir}[name].js`,
  chunkFileNames: `${assetsDir}[name].js`,
  assetFileNames: `${assetsDir}[name].[ext]`,
}

export default defineConfig({
  base: "./", // generate relative paths in html
  plugins: [
    directoryPlugin({ baseDir: __dirname }),
  ],
  build: {
    target: 'esnext',
    minify: false, // smaller git diffs
    rollupOptions: {
      input: 'prosemirror-versions.html', // default: index.html
      output: {
        ...outputDefaults,
      }
    },
  },
  esbuild: {
    keepNames: true, // keep names of functions and classes
  },
});
```

</details>

**Comment by wesbos** [comment]
Ohhhh gotcha! This plugin isn't for built sites, it's for dev mode. Could it be helpful in preview mode?

**Comment by wesbos** [comment]
Oh and if you get a 404, it's because you need to create an index.html with the tag from the readme

**Comment by milahu** [comment]
> you need to create an index.html with the tag from the readme

aah. "read the manual ..."
but thats unexpected.
this should work without any index.html, just like apache httpd directory listings

> Could it be helpful in preview mode?

yes. other http servers can do it too ... there is probably in upstream issue at vite

**Comment by wesbos** [comment]
Yeah I wish it would but I don't know how to catch the 404 and display the HTML file. Maybe I can dig into it more

**Comment by milahu** [comment]
> there is probably in upstream issue at vite

surprise, i made that issue ^^ https://github.com/vitejs/vite/issues/2818

sirv: https://github.com/lukeed/sirv/issues/111

workaround: to serve the `dist/` folder, use a static [http server](https://npm.io/search/keyword%3Ahttp-server) with directory listing

```
npm i http-server
npx http-server dist/
```

**Comment by wesbos** [comment]
The fix for this might lie in a custom middlware function. Or during the config, we could just create the file if it doesn't exist

**Comment by wesbos** [comment]
Okay in version 1.4.1 this now will create an index.html for you - much nicer! 

<img width="861" alt="Screenshot 2023-01-03 at 1 04 10 PM" src="https://user-images.githubusercontent.com/176013/210416450-a32fc947-e946-433b-bb70-1ef2f78c0d7f.png">

**Comment by milahu** [comment]
i didnt test but ... is that index file dynamic? (does it update when i add/remove files?)
this sounds like a quick hack, sounds like "custom middlware" would be a better solution
also for directory listings in subfolders
sorry for nagging ^^

**Comment by wesbos** [comment]
Of course it's dynamic - that's the whole point of this plugin. It even has HMR for lice reloads when a file is added, changed or removed. Give it a shot! Would love to find a middleware solution, but I can't find out how to do that, and still have vite parse the HTML file

**Comment by milahu** [comment]
> Give it a shot!

```sh
cd $(mktemp -d)
npm init -y 
pnpm i https://github.com/wesbos/vite-plugin-list-directory-contents
cat node_modules/vite-plugin-list-directory-contents/package.json | jq -r .version 
# 1.4.3
# workaround. with "install from git", the dist/ files are not built
# fix: "prepare" script should be "vite build"
( cd node_modules/vite-plugin-list-directory-contents && npm run build )
pnpm i vite 
mkdir dist
echo hello >dist/hello.txt
cat >vite.config.js <<'EOF'
import { defineConfig } from "vite";
import { directoryPlugin } from "vite-plugin-list-directory-contents";

export default defineConfig({
  plugins: [directoryPlugin({ baseDir: __dirname })],
});
EOF
stat index.html 
# stat: cannot statx 'index.html': No such file or directory
# -> ok
npx vite preview
# browser says: Error: Cannot GET /
# ... because configureServer is never called
npx vite dev
npx vite serve
# works, but only for the root folder. subfolders like dist/ are not listed
```

https://github.com/wesbos/vite-plugin-list-directory-contents/commit/94365be3f3e5a0ee353aed3a7583f7f6362c9c1d#diff-b72c2a6d80daeb87d4852346d0f86bdb7c15f767737a0e1336a7070d9e31d271R52

```
    <link rel="icon" href="https://fav.farm/🔥" />
```

should use offline assets (or no icon, or inlined icon via data url)

```
        }, 1000); // add a delay because Vite clears the console
```

haha, nice workaround for vite's `clearScreen:true` bug
(when you let gui people decide whats good for your console...)

```
![](https://wes.io/YEuDPod4/content.png)
```

should use offline assets (or no screenshot, or webp-compressed screenshot, or html "demo")

> 3. The first time it's run, the plugin will create an `index.html` for you in your `baseDir`. You can put anything in this file, and it will be processed by vite, but the important part is the `{%DIRECTORY%}` template tag that will be replaced with the directory listing.

aah, nice

but still, `npx vite preview` should not modify the files in dist/
so i still want that middleware solution ; )

**Comment by wesbos** [comment]
Looking forward to the PR!
