### ISSUE TITLE
Build errors when using directoryPlugin

### ISSUE THREAD

**Issue by NPanayotov** [wesbos/vite-plugin-list-directory-contents#5]
Hey,
I'm getting a build error when I try to use the plugin.

I have to mention that I changed the file structure and I'm using this for a static HTML/JS project.

![image](https://user-images.githubusercontent.com/13221604/207835693-7e117877-9c9c-4664-b747-909804760a2e.png)

![image](https://user-images.githubusercontent.com/13221604/207835287-d36a2b1a-20a8-4a3c-ba3d-92721030d3b5.png)

Config file:

```
import { resolve } from 'path';
import path from 'path';
import { defineConfig } from 'vite';
import glob from 'glob';
import handlebars from 'vite-plugin-handlebars';
import { directoryPlugin } from 'vite-plugin-list-directory-contents';

const outDir = resolve(__dirname, 'public');

export default defineConfig({
	plugins: [
		directoryPlugin({ baseDir: __dirname }),
		handlebars({
			partialDirectory: resolve(__dirname, 'partials'),
		}),
	],
	build: {
		outDir,
		rollupOptions: {
			input: glob.sync(path.resolve(__dirname, "", "*.html")),
			output: {
				assetFileNames: "assets/[name].[ext]",
				entryFileNames: `assets/[name].js`,
				chunkFileNames: `assets/[name].js`,
			},
		},
		emptyOutDir: false,
		minify: false,
	},
});
```

**Comment by wesbos** [comment]
Hmm interesting - this is not meant to be used for building sites - just for the dev server.  I wonder how to opt out of build with a vite plugin..

**Comment by wesbos** [comment]
Fixed in vite-plugin-list-directory-contents@1.2.2!

**Comment by NPanayotov** [comment]
Happy New Year! 

Thank you for looking into this.

I tested on my side, however, the fix doesn't seem to work.

Here is the error:

```
$ vite build
vite v4.0.3 building for production...
✓ 5 modules transformed.
Generated an empty chunk: "index".
rendering chunks (2)...[vite:build-html] Cannot read properties of undefined (reading 'replace')
error during build:
TypeError: Cannot read properties of undefined (reading 'replace')
    at transformIndexHtml (file:///Users/nate/base-template/vite/vite-template/node_modules/vite-plugin-list-directory-contents/dist/plugin.mjs:35:68)
    at applyHtmlTransforms (file:///Users/nate/base-template/vite/vite-template/node_modules/vite/dist/node/chunks/dep-0bae2027.js:35783:27)
    at Object.generateBundle (file:///Users/nate/base-template/vite/vite-template/node_modules/vite/dist/node/chunks/dep-0bae2027.js:35690:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bundle.generate (file:///Users/nate/base-template/vite/vite-template/node_modules/rollup/dist/es/shared/rollup.js:16719:9)
    at async file:///Users/nate/base-template/vite/vite-template/node_modules/rollup/dist/es/shared/rollup.js:24983:27
    at async catchUnfinishedHookActions (file:///Users/nate/base-template/vite/vite-template/node_modules/rollup/dist/es/shared/rollup.js:24022:20)
    at async doBuild (file:///Users/nate/base-template/vite/vite-template/node_modules/vite/dist/node/chunks/dep-0bae2027.js:44492:22)
    at async build (file:///Users/nate/base-template/vite/vite-template/node_modules/vite/dist/node/chunks/dep-0bae2027.js:44321:16)
    at async CAC.<anonymous> (file:///Users/nate/base-template/vite/vite-template/node_modules/vite/dist/node/cli.js:808:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

You can see my implementation here - https://github.com/NPanayotov/vite-template

I assume the issue may be caused by the `rollup`  plugin.

**Comment by NPanayotov** [comment]
Okay, so I figured it out.

If you pass the index file to the `rollupOptions` input it causes the error.

However, if you exclude this file from the glob array of files everything works fine.

**Comment by wesbos** [comment]
Can you show me an example of how you are excluding it? Ideally you won’t need to cod gourd anything with this plugin

**Comment by wesbos** [comment]
From your output- it seems like this plugin is still running during build - which it shouldn't. TRy update to the latest - maybe I forgot to ship the build!

**Comment by NPanayotov** [comment]
I'm using `yarn build` to build the source files.  I'm also using the latest plugin version.

Anyway, excluding the index file from the build input seems to be working for me.

Thank you for looking into it.

**Comment by wesbos** [comment]
no problem! I cloned your repo because you still shouldn't have to do that, I appreciate the example. Will take a closer look

**Comment by wesbos** [comment]
Got it! I had switched the package "type" to "module", but didn't update the exports in package.json, so you were just getting the old version of the package without the fixes :) 

So no need to exclude the file from your config if you don't want to 

<img width="578" alt="Screenshot 2023-01-03 at 10 14 32 AM" src="https://user-images.githubusercontent.com/176013/210385720-1b891747-b1fe-482b-a251-7ac6763da58b.png">

**Comment by NPanayotov** [comment]
Thank you so much for taking the time to look into this sir.

Cheers 🍻

**Comment by wesbos** [comment]
thanks for finding a bug :) Have a good one!
